### ISSUE TITLE
Bugs with the 0.2.4 update

### ISSUE THREAD

**Issue by allmudbloods** [chandler-stimson/live-stream-downloader#14]
Hey!
After the new update, I can't download stuff like before anymore. When I select a certain resolution of the video, it downloads another resolution. Futhermore, it's not dowloading the full lenght videos (I was trying to download one with 1 hour and a half, and it downloads only 1 hour or 50 minutes, for example). I tried to repeat the process several times, it changes the running time, but I never get the full lenght thing.

Thank you!

**Comment by Onomatopoesie** [comment]
It was perfect before the update. What originally could be downlowded perfectly with and only with this add-on, now "DataError: AES key data must be 128 or 256 bits".
Originally this add-on will download the video automatically after I click, and there is just a number on the icon from 1% to 100%, and there will be a ".ts" file on my disk. Perfectly what I need.
Now, with the new update, after I click, there is a new downlowding window (which I think is superfluous), asking me to save as ".mkv", and after that, it may or may not download the video for a few seconds, and then, "DataError: AES key data must be 128 or 256 bits".
I think the version before the new update is so perfect. I really really beg you to resume what it was, or give an independent version of that, otherwise I cannot download what I really need! So much thanks!!!

**Comment by chandler-stimson** [comment]
Can you provide an example page?

**Comment by allmudbloods** [comment]
Actually it's a site from an online course I'm taking, it needs to login... Is there any private way I can send you the M3U8 link, so you can test it?

**Comment by chandler-stimson** [comment]
I don't think the M3U8 link works on my side since to fetch the resources it needs the credentials. Anyhow you can send the link to my email address `chandler[dot]stimson[at]gmail.com`

**Comment by allmudbloods** [comment]
Okay, I'll be sending you it right now!

**Comment by chandler-stimson** [comment]
You can also try this test version;
https://github.com/chandler-stimson/live-stream-downloader/issues/15#issuecomment-1028599650

**Comment by allmudbloods** [comment]
I'm gonna try it. Just sent you the email by the way!

**Comment by chandler-stimson** [comment]
I think the bug is fixed on 0.2.5 release. You can either wait for the WebStore version or give it a try now

1. Open "chrome://extensions" in a browser tab
2. Turn the developer mode on
3. Disable the current version
4. Drop [live-stream-downloader.zip](https://github.com/chandler-stimson/live-stream-downloader/files/7994210/live-stream-downloader.zip) to this page.

**Comment by chandler-stimson** [comment]
About the quality mismatch:

Whenever you select the "master.m3u8" wait for the extension to display the quality selector. If the window is not focused, it automatically selects the first quality which in your case is the lowest quality.

**Comment by allmudbloods** [comment]
Thank you so much! It's now working perfectly with the 0.2.5 version!
