### ISSUE TITLE
[Feature request] Filter illegal characters from filename

### ISSUE THREAD

**Issue by gruppler** [chandler-stimson/live-stream-downloader#46]
When using `[title]` in the filename format, I'm unable to download the file because it contains illegal characters ("|").

**Comment by gruppler** [comment]
It would also be nice to see the `meta.name` in the list regardless of the filename format, since using `[title]` makes all the files appear the same in the download selection list. Perhaps underneath the generated filename, you could also show the `meta.name`?

**Comment by chandler-stimson** [comment]
The extension tries to extract the filename from the "Content-Disposition" header. If this fails, it tries to extract the name from the link. So, we are not using page titles. Can you provide an example?

**Comment by gruppler** [comment]
You are not using page titles, even if I set the filename format to `[title]`?

Unfortunately, the videos I'm trying to download are behind a paywall so I would have to find another example. But I can see in the page title there is a pipe character (`|`) which is illegal at least on Windows.

**Comment by gruppler** [comment]
![image](https://github.com/chandler-stimson/live-stream-downloader/assets/301190/9771750e-0781-46d8-9118-296b1714b5f5)
Here's a screenshot from a recent attempt.

**Comment by chandler-stimson** [comment]
Please try the latest commit to see if the issue is fixed or not

- Download the project:
  -   https://github.com/chandler-stimson/live-stream-downloader/archive/refs/heads/master.zip
- Extract to a local directory
- Open "chrome://extensions/" in a browser tab and turn the developer mode on
- Drop the "v3" directory to this view.

**Comment by gruppler** [comment]
I installed the unpacked extension and set my filename format to `[title]`.
The download succeeded, but when the Save dialog popped up, the name was "_undefined.txt" and type was ".txt". When I selected "All files" as the type and manually added the ".mkv" extension, I was able to successfully open the file in a video player.
![image](https://github.com/chandler-stimson/live-stream-downloader/assets/301190/4c9b32b8-4718-4eeb-b1d1-3eded0f6ab3d)

**Comment by vertigo220** [comment]
Using the latest version, files with illegal characters download but they end up as "undefined'.txt" files.

**Comment by chandler-stimson** [comment]
@vertigo220 
This issue is related to the OS, browser and the type of the illegal chars. I need example to fix it

**Comment by vertigo220** [comment]
Main issues is with /'s, with Brave on Windows. Or do you need an example link?

**Comment by chandler-stimson** [comment]
You mean like `file's.txt`?

**Comment by vertigo220** [comment]
Not sure what you mean. If the page title is e.g. "Page / Title" it will result in "undefined.txt" because the slash breaks it.

**Comment by vertigo220** [comment]
@chandler-stimson I assume this issue won't be fixed as it's been over 7 months?

**Comment by chandler-stimson** [comment]
@vertigo220 this should be fixed by the latest commit. Give it a try and report back

**Comment by vertigo220** [comment]
@chandler-stimson Thanks! I look forward to testing it. Not sure how it works since the update hasn't hit the store yet, but what would really be helpful would be a configuration that would allow setting what to replace different illegal characters with, so instead of them just being left out or replaced with a space they could be replaced with something recognizable. I have a system where I use specific characters for the various illegal ones, and I'd really like to be able to have it automatically use them when naming the files.
